// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "HHRopeClimb.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "../Commands/HHRopeClimbJoy.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

HHRopeClimb::HHRopeClimb() : Subsystem("HHRopeClimb") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    hHSCRopeClimb = RobotMap::hHRopeClimbHHSCRopeClimb;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}

void HHRopeClimb::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        SetDefaultCommand(new HHRopeClimbJoy());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
void HHRopeClimb::hHRopeClimbUp()
{
	hHSCRopeClimb->Set(-0.95);
}
void HHRopeClimb::hHRopeClimbDown()
{
	hHSCRopeClimb->Set(0.95);
}
void HHRopeClimb::hHRopeClimbStop()
{
	hHSCRopeClimb->Set(0.0);
	}
void HHRopeClimb::hHRopeClimbJoyYIn(double rCJoyYIn)
{
//make sure it is a negative. for only climb up.
	if(rCJoyYIn <0)
	{
		hHSCRopeClimb->Set(rCJoyYIn);
	}
	else
	{
		hHSCRopeClimb->Set(0.0);
	}
}

// Put methods for controlling this subsystem
// here. Call these from Commands.

