// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "HHACDriveWaitInput.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

HHACDriveWaitInput::HHACDriveWaitInput(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(Robot::chassis.get());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::hHBaseDrive.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void HHACDriveWaitInput::Initialize() {
	SetTimeout(0.0);
	if (SmartDashboard::GetNumber("DS-Auto-Delay-Seconds",0.0)<=15)
	{
		SetTimeout(SmartDashboard::GetNumber("DS-Auto-Delay-Seconds",0.0));
	}
	else
	{
		SetTimeout(0.0);
	}
}

// Called repeatedly when this Command is scheduled to run
void HHACDriveWaitInput::Execute() {
	Robot::hHBaseDrive->hHTankDrive(0.0,0.0);
}

// Make this return true when this Command no longer needs to run execute()
bool HHACDriveWaitInput::IsFinished() {
	return (IsTimedOut());
}

// Called once after isFinished returns true
void HHACDriveWaitInput::End() {
	Robot::hHBaseDrive->hHTankDrive(0.0,0.0);
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void HHACDriveWaitInput::Interrupted() {
	End();
}
