// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "HHACDS2WallToLiftStraight.h"
//#include "Commands/HHACDriveWaitInput.h"
#include "HHACDriveWaitInput.h"
#include "Commands/HHACBaseLineCross.h"
#include "Commands/HHACDriveToLift.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

HHACDS2WallToLiftStraight::HHACDS2WallToLiftStraight() {
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
              // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
                AddSequential(new HHACDriveWaitInput());
        AddSequential(new HHACBaseLineCross());
        AddSequential(new HHACDriveToLift());
              // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
 }
