// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#ifndef HHACDRIVEDISTFASTTURNRIGHT1DRIVEDISTSLOW_H
#define HHACDRIVEDISTFASTTURNRIGHT1DRIVEDISTSLOW_H

#include "Commands/CommandGroup.h"
#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class HHACDriveDistFastTurnRight1DriveDistSlow: public CommandGroup {
public:

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	HHACDriveDistFastTurnRight1DriveDistSlow();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

private:
	double hHDistDS;
};

#endif
